import type { Product, ProductVariant, Review, Spec } from "./types";

const range = (id: string, km: number, speed: number, battery: string, mrp: number, offer: number): ProductVariant => ({
  id,
  label: `${km} km`,
  rangeKm: km,
  topSpeedKmh: speed,
  battery,
  mrp,
  offerPrice: offer,
  stock: 4,
});

const spec = (label: string, value: string): Spec => ({ label, value });
const review = (id: string, author: string, rating: number, comment: string): Review => ({ id, author, rating, comment });

type Seed = Pick<
  Product,
  "id" | "name" | "category" | "description" | "rating" | "reviewCount" | "images" | "featured" | "trending" | "variants" | "specifications" | "reviews"
>;

const scooty = (seed: Seed): Product => ({
  ...seed,
  brand: "Devbhoomi",
  sellerId: "showroom",
  cities: [],
  color: "",
  colors: [],
  modelName: "",
  motorWatt: 0,
  chargerAmp: 0,
  chargeHours: 0,
  trashed: false,
  trashedAt: 0,
  sellerName: "",
  listedAt: 0,
});

export const sampleProducts: Product[] = [
  scooty({
    id: "spark-city",
    name: "Spark City",
    category: "City",
    description: "A light city scooty for college runs, market trips, and quiet lanes.",
    rating: 4.3,
    reviewCount: 128,
    images: ["mint", "forest", "slate"],
    featured: true,
    trending: false,
    variants: [range("r90", 90, 55, "2.0 kWh", 84_999, 74_999), range("r110", 110, 65, "2.5 kWh", 99_999, 89_999)],
    specifications: [
      spec("Motor", "1.8 kW hub"),
      spec("Charge time", "4.5 hours"),
      spec("Brake", "Disc + drum"),
      spec("Warranty", "3 years / 30,000 km"),
      spec("Weight", "89 kg"),
    ],
    reviews: [
      review("s1", "Meera Joshi", 5, "Easy in traffic and the seat stays comfortable on the ridge road."),
      review("s2", "Aman Rawat", 4, "Home charging is enough for a week of campus rides."),
    ],
  }),
  scooty({
    id: "hill-glide",
    name: "Hill Glide",
    category: "Family",
    description: "Extra range and a roomy seat for family trips around the hills.",
    rating: 4.6,
    reviewCount: 86,
    images: ["forest", "gold", "mint"],
    featured: true,
    trending: true,
    variants: [range("r120", 120, 65, "3.0 kWh", 114_999, 104_999), range("r140", 140, 70, "3.2 kWh", 124_999, 109_999)],
    specifications: [
      spec("Motor", "2.2 kW"),
      spec("Charge time", "5 hours"),
      spec("Ground clearance", "165 mm"),
      spec("Warranty", "3 years battery"),
      spec("Seating", "Split seat, 2-up"),
    ],
    reviews: [
      review("h1", "Priya Negi", 5, "Climbs the Dehradun bypass without feeling strained."),
      review("h2", "Rohit Singh", 4, "The 140 km pack is the one to buy if you leave town."),
    ],
  }),
  scooty({
    id: "volt-sport",
    name: "Volt Sport",
    category: "Sport",
    description: "Sharper pickup for riders who want an electric scooty with a sport feel.",
    rating: 4.4,
    reviewCount: 64,
    images: ["slate", "forest", "lime"],
    featured: false,
    trending: true,
    variants: [range("r100", 100, 80, "3.0 kWh", 124_999, 114_999), range("r120", 120, 85, "3.4 kWh", 139_999, 129_999)],
    specifications: [
      spec("Motor", "3.0 kW"),
      spec("Charge time", "5.5 hours"),
      spec("Top speed", "Up to 85 km/h"),
      spec("Brake", "Dual disc"),
      spec("Warranty", "3 years"),
    ],
    reviews: [review("v1", "Kabir Ali", 4, "Pickup is the reason I switched from petrol.")],
  }),
  scooty({
    id: "cargo-haul",
    name: "Cargo Haul",
    category: "Cargo",
    description: "A carrier scooty for shop deliveries and showroom runs.",
    rating: 4.1,
    reviewCount: 41,
    images: ["gold", "forest", "slate"],
    featured: false,
    trending: true,
    variants: [range("r80", 80, 50, "3.0 kWh", 109_999, 99_999), range("r100", 100, 55, "3.6 kWh", 129_999, 119_999)],
    specifications: [
      spec("Carrier", "Rear rack, 40 kg"),
      spec("Motor", "2.0 kW"),
      spec("Charge time", "6 hours"),
      spec("Warranty", "3 years"),
      spec("Use", "Delivery and shop hops"),
    ],
    reviews: [review("c1", "Sanjay Pant", 4, "The rack holds a full grocery run. The 100 km pack is worth it.")],
  }),
  scooty({
    id: "peak-premium",
    name: "Peak Premium",
    category: "Premium",
    description: "Our flagship ride: long range, smooth power, and a showroom finish.",
    rating: 4.8,
    reviewCount: 53,
    images: ["lime", "gold", "forest"],
    featured: true,
    trending: true,
    variants: [range("r140", 140, 75, "3.6 kWh", 154_999, 144_999), range("r160", 160, 80, "4.0 kWh", 174_999, 159_999)],
    specifications: [
      spec("Motor", "3.2 kW"),
      spec("Charge time", "6 hours"),
      spec("Display", "Digital, Bluetooth"),
      spec("Brake", "Dual disc, CBS"),
      spec("Warranty", "5 years battery"),
    ],
    reviews: [
      review("p1", "Ananya Bisht", 5, "Quiet, finished well, and the longer pack covers a full hill day."),
      review("p2", "Vikram Chauhan", 5, "Feels like a proper showroom scooter, not a kit."),
    ],
  }),
  scooty({
    id: "campus-zip",
    name: "Campus Zip",
    category: "City",
    description: "An easy first EV scooty. Charge at home and skip the petrol queue.",
    rating: 4.2,
    reviewCount: 97,
    images: ["mint", "lime", "gold"],
    featured: true,
    trending: false,
    variants: [range("r75", 75, 50, "1.8 kWh", 79_999, 69_999), range("r90", 90, 55, "2.0 kWh", 84_999, 74_999)],
    specifications: [
      spec("Motor", "1.5 kW"),
      spec("Charge time", "4 hours"),
      spec("Brake", "Drum"),
      spec("Warranty", "3 years"),
      spec("Best for", "Short city hops"),
    ],
    reviews: [review("z1", "Neha Gupta", 4, "Simple and light. The 90 km option is the safer buy.")],
  }),
];
